# Generated by Django 5.0 on 2024-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_APP', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/None/Noimage.jpg', upload_to='images/'),
        ),
    ]
