# Generated by Django 4.2.8 on 2023-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1983-03-10', verbose_name=()),
            preserve_default=False,
        ),
    ]
